name = "goalserve-sportsbook-frontend"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "../src/static"
entry-point = "."

[env.production]
name = "goalserve-sportsbook-frontend"
workers_dev = true

[env.staging]
name = "goalserve-sportsbook-frontend-staging"
workers_dev = true
