app = "goalserve-sportsbook-backend"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  FLASK_ENV = "production"
  IS_PRODUCTION = "true"
  IS_LOCAL = "false"
  HOST = "0.0.0.0"
  DEBUG = "false"
  PORT = "8080"
  # ensure env.local never overrides prod values on Fly
  IGNORE_ENV_LOCAL = "1"

[processes]
  app = "python run.py"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ["app"]

[[checks]]
  name = "http"
  type = "http"
  interval = "15s"
  timeout = "3s"
  grace_period = "20s"
  [checks.http]
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 2048

[[mounts]]
  source = "goalserve_data"
  destination = "/app/data"
